<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        $dimensions = (int) config('embedding.dimensions', 384);

        Schema::create('posts', function (Blueprint $table) use ($dimensions) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->text('caption');
            $table->string('image_url')->nullable();

            // Semantic-search vector (pgvector). Nullable so a post can exist
            // before its embedding is (re)generated by the Phase 3 pipeline.
            $table->vector('embedding', $dimensions)->nullable();

            $table->timestamps();

            $table->index('created_at');
        });

        // Approximate-nearest-neighbour index for cosine similarity search.
        DB::statement(
            'CREATE INDEX posts_embedding_hnsw_idx ON posts USING hnsw (embedding vector_cosine_ops)'
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('posts');
    }
};
